#!/bin/sh /etc/rc.common

. /lib/functions.sh

USE_PROCD=1
START=95
STOP=10

SERVICE_NAME="nora"

start_service() {
	local install_dir

	config_load nora
	config_get install_dir config install_dir '/opt/nora'
	/usr/libexec/nora-control render-config >/dev/null || return 1

	procd_open_instance
	procd_set_param env NORA_CONFIG_PATH="$install_dir/config/config.toml"
	procd_set_param command "$install_dir/bin/nora"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	return 0
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "nora"
}
