#!/bin/sh /etc/rc.common

. /lib/functions.sh

START=99
USE_PROCD=1

start_service() {
	config_load template

	local enabled
	config_get_bool enabled config enabled 0

	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /bin/sh -c 'while sleep 3600; do :; done'
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	stop
	start
}
